<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;
use App\Models\User;
use App\Models\Job;
use App\Models\Training;
use App\Models\Service;
use App\Models\Notification;

class DatabaseSeeder extends Seeder
{
    public function run(): void
    {
        // ── Demo Users ────────────────────────────────────────────────────────
        User::firstOrCreate(['email' => 'admin@pgrkam.gov.in'], [
            'name'       => 'PGRKAM Admin',
            'phone'      => '0172-2664001',
            'password'   => Hash::make('password'),
            'role'       => 'admin',
            'district'   => 'Chandigarh',
            'is_active'  => true,
        ]);

        User::firstOrCreate(['email' => 'user@pgrkam.gov.in'], [
            'name'       => 'Harpreet Singh',
            'phone'      => '9876543210',
            'password'   => Hash::make('password'),
            'role'       => 'user',
            'district'   => 'Ludhiana',
            'is_active'  => true,
        ]);

        // ── Services ──────────────────────────────────────────────────────────
        $services = [
            ['title' => 'Government Jobs',        'icon' => '🏛️', 'color' => 'blue', 'path' => '/jobs',               'sort_order' => 1],
            ['title' => 'Private Jobs',           'icon' => '🏢', 'color' => 'blue', 'path' => '/jobs?type=private',  'sort_order' => 2],
            ['title' => 'Skill Training',         'icon' => '🎓', 'color' => 'blue', 'path' => '/training',           'sort_order' => 3],
            ['title' => 'Resume Builder',         'icon' => '📄', 'color' => 'blue', 'path' => '/resume',             'sort_order' => 4],
            ['title' => 'Career Counselling',     'icon' => '💬', 'color' => 'blue', 'path' => '/counselling',        'sort_order' => 5],
            ['title' => 'Employment Schemes',     'icon' => '📋', 'color' => 'blue', 'path' => '/services',           'sort_order' => 6],
            ['title' => 'Apprenticeship Portal',  'icon' => '🔧', 'color' => 'blue', 'path' => '/jobs',               'sort_order' => 7],
            ['title' => 'Self Employment Loans',  'icon' => '💰', 'color' => 'blue', 'path' => '/services',           'sort_order' => 8],
            ['title' => 'Mukhyamantri Rozgar',    'icon' => '🌾', 'color' => 'blue', 'path' => '/services',           'sort_order' => 9],
            ['title' => 'Women Entrepreneurship', 'icon' => '👩', 'color' => 'blue', 'path' => '/services',           'sort_order' => 10],
            ['title' => 'Disability Employment',  'icon' => '♿', 'color' => 'blue', 'path' => '/services',           'sort_order' => 11],
            ['title' => 'Overseas Placement',     'icon' => '✈️', 'color' => 'blue', 'path' => '/services',           'sort_order' => 12],
        ];
        foreach ($services as $s) {
            Service::firstOrCreate(['title' => $s['title']], array_merge($s, ['is_active' => true]));
        }

        // ── Real Punjab Jobs ──────────────────────────────────────────────────
        $jobs = [
            // --- GOVERNMENT JOBS ---
            [
                'title'                => 'Junior Clerk (Revenue Dept.)',
                'department'           => 'Department of Revenue, Rehabilitation & Disaster Management',
                'location'             => 'Chandigarh',
                'type'                 => 'government',
                'salary_range'         => '₹19,900 – ₹63,200',
                'vacancies'            => 180,
                'application_deadline' => '2026-07-15',
                'posted_on'            => '2026-05-01',
                'description'          => 'Punjab Government invites applications from eligible candidates for the post of Junior Clerk in the Department of Revenue. Candidates will handle revenue records, file management, and assist officers in day-to-day administrative work.',
                'qualifications'       => ['10+2 pass from a recognized board', 'Diploma in Computer Applications (DCA)', 'Punjabi language proficiency at Matric level', 'Typing speed: 30 WPM (English) or 25 WPM (Punjabi)'],
            ],
            [
                'title'                => 'Software Developer (Grade-B)',
                'department'           => 'Punjab Information & Communication Technology Corporation (PICTC)',
                'location'             => 'Mohali',
                'type'                 => 'government',
                'salary_range'         => '₹44,900 – ₹1,42,400',
                'vacancies'            => 45,
                'application_deadline' => '2026-07-31',
                'posted_on'            => '2026-05-05',
                'description'          => 'PICTC requires Software Developers to design, develop and maintain government web portals and digital services. The role involves full-stack development using PHP/Laravel or Node.js, database management with MySQL/PostgreSQL, and integration with state government APIs.',
                'qualifications'       => ['B.Tech/B.E. in Computer Science or IT (60% aggregate)', 'Knowledge of PHP, Laravel or Node.js', 'Experience with MySQL/PostgreSQL', 'Understanding of REST APIs and microservices'],
            ],
            [
                'title'                => 'Sub Inspector (Punjab Police)',
                'department'           => 'Punjab Police',
                'location'             => 'Amritsar',
                'type'                 => 'government',
                'salary_range'         => '₹35,400 – ₹1,12,400',
                'vacancies'            => 560,
                'application_deadline' => '2026-08-10',
                'posted_on'            => '2026-05-08',
                'description'          => 'Punjab Police is recruiting Sub Inspectors for law enforcement duties. Selected candidates will be responsible for maintaining law and order, investigating crimes, managing police stations, and protecting public safety across Punjab.',
                'qualifications'       => ['Graduation from a recognized university', 'Age: 18-28 years (relaxation applicable)', 'Height: Male 170cm / Female 157cm', 'Physical fitness test mandatory', 'Clean criminal record'],
            ],
            [
                'title'                => 'Agriculture Development Officer',
                'department'           => 'Department of Agriculture, Punjab',
                'location'             => 'Ludhiana',
                'type'                 => 'government',
                'salary_range'         => '₹28,900 – ₹91,300',
                'vacancies'            => 92,
                'application_deadline' => '2026-07-20',
                'posted_on'            => '2026-05-03',
                'description'          => 'The Agriculture Department Punjab seeks Agriculture Development Officers to promote modern farming techniques, distribute subsidies, monitor crop production, and assist farmers with government schemes like MSP, crop insurance, and Kisan Credit Card.',
                'qualifications'       => ['B.Sc. Agriculture from a recognized university', 'Knowledge of Punjabi (Matric level)', 'Valid driving license', 'Age: 21-37 years'],
            ],
            [
                'title'                => 'Staff Nurse (Civil Hospital)',
                'department'           => 'Department of Health & Family Welfare, Punjab',
                'location'             => 'Jalandhar',
                'type'                 => 'government',
                'salary_range'         => '₹30,900 – ₹97,800',
                'vacancies'            => 320,
                'application_deadline' => '2026-07-25',
                'posted_on'            => '2026-05-06',
                'description'          => 'Punjab Health Department invites applications for Staff Nurse positions at Civil Hospitals across Punjab. Duties include patient care, administering medications, assisting surgeons, maintaining medical records, and working in emergency ward rotations.',
                'qualifications'       => ['B.Sc. Nursing or GNM (General Nursing & Midwifery)', 'Registered with Punjab Nursing Council', 'Age: 18-37 years', 'Preference to candidates with ICU/OT experience'],
            ],
            [
                'title'                => 'Assistant Engineer (PWD B&R)',
                'department'           => 'Public Works Department (Buildings & Roads)',
                'location'             => 'Chandigarh',
                'type'                 => 'government',
                'salary_range'         => '₹47,600 – ₹1,51,100',
                'vacancies'            => 68,
                'application_deadline' => '2026-08-05',
                'posted_on'            => '2026-05-10',
                'description'          => 'PWD (B&R) Punjab is recruiting Assistant Engineers for supervision of road and building construction projects. Role involves preparing design estimates, supervising contractors, quality control of materials, and maintaining project records.',
                'qualifications'       => ['B.E./B.Tech in Civil Engineering (55% aggregate)', 'Age: 18-37 years', 'Punjabi at Matric level', 'Knowledge of AutoCAD preferred'],
            ],
            [
                'title'                => 'Patwari (Revenue Girdawar)',
                'department'           => 'Department of Revenue, Punjab',
                'location'             => 'Ferozepur',
                'type'                 => 'government',
                'salary_range'         => '₹19,900 – ₹63,200',
                'vacancies'            => 1152,
                'application_deadline' => '2026-07-10',
                'posted_on'            => '2026-05-02',
                'description'          => 'The Revenue Department Punjab is conducting a large-scale recruitment of Patwaris. Patwaris maintain land records, prepare and update girdawari reports, assist in demarcation of land boundaries, and support revenue courts.',
                'qualifications'       => ['Matriculation (10th pass)', 'Punjabi at Matric level (mandatory)', 'Knowledge of Punjab land records system', 'Age: 18-35 years', 'Computer literacy preferred'],
            ],
            [
                'title'                => 'Electrician Grade-I (PSPCL)',
                'department'           => 'Punjab State Power Corporation Limited (PSPCL)',
                'location'             => 'Patiala',
                'type'                 => 'government',
                'salary_range'         => '₹25,000 – ₹81,000',
                'vacancies'            => 2400,
                'application_deadline' => '2026-07-30',
                'posted_on'            => '2026-05-07',
                'description'          => 'PSPCL is hiring Electricians for installation, maintenance and repair of electrical equipment including transformers, switch gear, power lines, substations and metering equipment across Punjab.',
                'qualifications'       => ['ITI (Electrician trade) with NAC certificate', 'Wireman license from Punjab Govt.', 'Age: 18-37 years', 'Physically fit (eyesight required)'],
            ],
            [
                'title'                => 'PGT Computer Science (Teacher)',
                'department'           => 'Department of School Education, Punjab',
                'location'             => 'Ludhiana',
                'type'                 => 'government',
                'salary_range'         => '₹37,800 – ₹1,19,800',
                'vacancies'            => 135,
                'application_deadline' => '2026-07-18',
                'posted_on'            => '2026-05-04',
                'description'          => 'Punjab School Education Board is recruiting Post Graduate Teachers (PGT) in Computer Science for Government Senior Secondary Schools. The role involves teaching Class 11-12 students, preparing lesson plans, conducting practicals, and mentoring students.',
                'qualifications'       => ['M.Sc. Computer Science / B.Tech CS + B.Ed.', 'PSTET Paper-II qualified', 'Punjabi at Matric level', 'Age: 18-37 years'],
            ],
            [
                'title'                => 'Forest Guard',
                'department'           => 'Punjab Forest Department',
                'location'             => 'Gurdaspur',
                'type'                 => 'government',
                'salary_range'         => '₹19,900 – ₹63,200',
                'vacancies'            => 87,
                'application_deadline' => '2026-08-01',
                'posted_on'            => '2026-05-09',
                'description'          => 'Punjab Forest Department requires Forest Guards for protection and conservation of forest areas. Duties include patrolling forest areas, preventing illegal logging, fire prevention, wildlife protection, and maintaining forest records.',
                'qualifications'       => ['10+2 from recognized board', 'Age: 18-25 years', 'Height: 163cm (Male), 150cm (Female)', 'Physical fitness test required', 'Knowledge of local flora & fauna preferred'],
            ],
            [
                'title'                => 'Lab Technician (Grade-II)',
                'department'           => 'Department of Health & Family Welfare, Punjab',
                'location'             => 'Amritsar',
                'type'                 => 'government',
                'salary_range'         => '₹22,700 – ₹72,000',
                'vacancies'            => 200,
                'application_deadline' => '2026-07-22',
                'posted_on'            => '2026-05-05',
                'description'          => 'Health Department Punjab requires Lab Technicians for Government hospitals and PHCs. Role involves conducting diagnostic tests (blood, urine, culture, radiology), maintaining lab equipment, and reporting results to doctors.',
                'qualifications'       => ['DMLT (Diploma in Medical Lab Technology) or B.Sc. MLT', 'Registered with Punjab Para-Medical Council', 'Age: 18-37 years'],
            ],
            [
                'title'                => 'Canal Patwari (Irrigation Dept.)',
                'department'           => 'Department of Water Resources, Punjab',
                'location'             => 'Ferozepur',
                'type'                 => 'government',
                'salary_range'         => '₹19,900 – ₹63,200',
                'vacancies'            => 210,
                'application_deadline' => '2026-07-12',
                'posted_on'            => '2026-05-01',
                'description'          => 'The Irrigation Department Punjab invites applications for Canal Patwari to manage water distribution records, maintain canal outlets, record water usage, and coordinate with farmers for irrigation scheduling under the Bhakra and other canal systems.',
                'qualifications'       => ['Matriculation (10th pass)', 'Knowledge of Punjabi', 'Age: 18-35 years', 'Knowledge of irrigation systems preferred'],
            ],
            [
                'title'                => 'Data Entry Operator (DEO)',
                'department'           => 'Punjab Health Systems Corporation (PHSC)',
                'location'             => 'Mohali',
                'type'                 => 'government',
                'salary_range'         => '₹18,000 – ₹56,900',
                'vacancies'            => 340,
                'application_deadline' => '2026-06-30',
                'posted_on'            => '2026-05-01',
                'description'          => 'PHSC requires Data Entry Operators to enter patient data, manage health records on the HMIS portal, prepare reports, and support hospital administration with data management activities.',
                'qualifications'       => ['10+2 with Computer Science', 'Typing speed: 35 WPM (English)', 'DCA/PGDCA preferred', 'Age: 18-35 years'],
            ],

            // --- PRIVATE SECTOR JOBS ---
            [
                'title'                => 'Frontend Developer (React/Vue)',
                'department'           => 'Quark Systems Pvt. Ltd.',
                'location'             => 'Mohali',
                'type'                 => 'private',
                'salary_range'         => '₹40,000 – ₹80,000',
                'vacancies'            => 12,
                'application_deadline' => '2026-07-05',
                'posted_on'            => '2026-05-08',
                'description'          => 'Quark Systems is looking for Frontend Developers to build responsive web applications for international clients. You will work with React/Vue.js, REST APIs, and modern UI frameworks. Flexible work from office options available.',
                'qualifications'       => ['B.Tech/BCA in Computer Science', '2+ years experience in React.js or Vue.js', 'Knowledge of Tailwind CSS / Bootstrap', 'Git version control proficiency'],
            ],
            [
                'title'                => 'Customer Support Executive',
                'department'           => 'Concentrix India Pvt. Ltd.',
                'location'             => 'Amritsar',
                'type'                 => 'private',
                'salary_range'         => '₹15,000 – ₹22,000',
                'vacancies'            => 80,
                'application_deadline' => '2026-06-25',
                'posted_on'            => '2026-05-06',
                'description'          => 'Concentrix Amritsar centre is hiring Customer Support Executives for inbound voice process (domestic & international). Candidates will handle customer queries, resolve complaints, and provide service information. Cab facility available.',
                'qualifications'       => ['10+2 minimum', 'Good communication skills in Hindi/English', 'Basic computer knowledge', 'Freshers welcome', 'Flexible with rotational shifts'],
            ],
            [
                'title'                => 'Accountant (CA Inter / B.Com)',
                'department'           => 'Vardhman Textiles Ltd.',
                'location'             => 'Ludhiana',
                'type'                 => 'private',
                'salary_range'         => '₹28,000 – ₹45,000',
                'vacancies'            => 8,
                'application_deadline' => '2026-07-10',
                'posted_on'            => '2026-05-07',
                'description'          => 'Vardhman Textiles requires an experienced Accountant for GST compliance, accounts payable/receivable, bank reconciliation, P&L statements, and coordination with the finance team for monthly closing.',
                'qualifications'       => ['B.Com / CA Inter', 'Knowledge of Tally ERP 9 / Tally Prime', '2-5 years accounting experience', 'GST filing experience mandatory'],
            ],
            [
                'title'                => 'Warehouse Supervisor',
                'department'           => 'Delhivery Pvt. Ltd.',
                'location'             => 'Ludhiana',
                'type'                 => 'private',
                'salary_range'         => '₹25,000 – ₹35,000',
                'vacancies'            => 15,
                'application_deadline' => '2026-07-08',
                'posted_on'            => '2026-05-09',
                'description'          => 'Delhivery Ludhiana hub is hiring Warehouse Supervisors to manage daily inbound/outbound operations, inventory control, staff supervision, loading/unloading coordination, and MIS reporting.',
                'qualifications'       => ['Graduation in any stream', '2+ years experience in warehouse/logistics', 'Knowledge of WMS software', 'Two-wheeler for local travel'],
            ],
            [
                'title'                => 'Sales Executive (Field)',
                'department'           => 'HDFC Bank Ltd.',
                'location'             => 'Chandigarh',
                'type'                 => 'private',
                'salary_range'         => '₹18,000 – ₹28,000 + incentives',
                'vacancies'            => 30,
                'application_deadline' => '2026-06-28',
                'posted_on'            => '2026-05-08',
                'description'          => 'HDFC Bank is hiring Sales Executives for cross-selling banking products (savings accounts, credit cards, personal loans, insurance). Role involves visiting customers, achieving monthly targets, and building a customer portfolio.',
                'qualifications'       => ['Graduation in any stream', 'Age: 21-30 years', 'Two-wheeler with valid DL', 'Good communication skills', 'Freshers with good academic record may apply'],
            ],
            [
                'title'                => 'Graphic Designer',
                'department'           => 'Punjab Kesari Media Group',
                'location'             => 'Jalandhar',
                'type'                 => 'private',
                'salary_range'         => '₹22,000 – ₹38,000',
                'vacancies'            => 5,
                'application_deadline' => '2026-07-15',
                'posted_on'            => '2026-05-07',
                'description'          => 'Punjab Kesari is looking for a creative Graphic Designer to create newspaper layouts, digital banners, social media creatives, and marketing materials. Must have a strong portfolio in print and digital design.',
                'qualifications'       => ['Diploma/Degree in Graphic Design or related field', 'Proficiency in Adobe Photoshop, Illustrator, InDesign', '1-3 years experience', 'Portfolio required at interview'],
            ],
            [
                'title'                => 'Electrician / Wireman',
                'department'           => 'Havells India Ltd.',
                'location'             => 'Mohali',
                'type'                 => 'private',
                'salary_range'         => '₹18,000 – ₹28,000',
                'vacancies'            => 25,
                'application_deadline' => '2026-07-20',
                'posted_on'            => '2026-05-06',
                'description'          => 'Havells India requires Electricians/Wiremen for installation, commissioning and maintenance of electrical systems at residential and commercial project sites in and around Mohali/Chandigarh tricity.',
                'qualifications'       => ['ITI Electrician trade certificate', 'Wireman license preferred', '1+ year field experience', 'Willing to travel to project sites'],
            ],
            [
                'title'                => 'BPO Agent (Domestic Process)',
                'department'           => 'Infosys BPM Ltd.',
                'location'             => 'Chandigarh',
                'type'                 => 'private',
                'salary_range'         => '₹16,000 – ₹22,000',
                'vacancies'            => 100,
                'application_deadline' => '2026-06-30',
                'posted_on'            => '2026-05-05',
                'description'          => 'Infosys BPM Chandigarh is hiring BPO agents for domestic voice and back-office processes. Responsibilities include handling customer calls, data processing, complaint resolution, and maintaining quality standards.',
                'qualifications'       => ['10+2 minimum (Graduation preferred)', 'Fluent Hindi and basic English', 'Good typing speed (25+ WPM)', 'Freshers with good communication preferred', 'Rotational shifts'],
            ],
            [
                'title'                => 'Marketing Executive (Digital)',
                'department'           => 'Relaxo Footwear Ltd.',
                'location'             => 'Ludhiana',
                'type'                 => 'private',
                'salary_range'         => '₹22,000 – ₹35,000',
                'vacancies'            => 10,
                'application_deadline' => '2026-07-12',
                'posted_on'            => '2026-05-08',
                'description'          => 'Relaxo Footwear is looking for a Digital Marketing Executive to manage social media accounts, run Meta/Google Ad campaigns, create content, track campaign performance, and generate leads for the Punjab region.',
                'qualifications'       => ['BBA / B.Com / B.Sc. with Digital Marketing certification', 'Knowledge of Meta Ads, Google Ads, SEO', '1-2 years experience', 'Proficient in Canva/Adobe tools'],
            ],
            [
                'title'                => 'Security Guard (Mall Duty)',
                'department'           => 'G4S Secure Solutions India',
                'location'             => 'Amritsar',
                'type'                 => 'private',
                'salary_range'         => '₹14,000 – ₹18,000',
                'vacancies'            => 50,
                'application_deadline' => '2026-06-20',
                'posted_on'            => '2026-05-03',
                'description'          => 'G4S is hiring Security Guards for duty at Alpha One Mall, Amritsar. Duties include access control, patrolling premises, CCTV monitoring, crowd management, and emergency response. Uniforms and ID cards provided.',
                'qualifications'       => ['Minimum 10th pass', 'Age: 21-45 years', 'Height: 5\'6\' (Male), 5\'3\' (Female)', 'Ex-servicemen preferred', 'Medical fitness certificate required'],
            ],

            // --- MORE GOVERNMENT JOBS ---
            [
                'title'                => 'Veterinary Inspector',
                'department'           => 'Department of Animal Husbandry, Punjab',
                'location'             => 'Patiala',
                'type'                 => 'government',
                'salary_range'         => '₹28,900 – ₹91,300',
                'vacancies'            => 74,
                'application_deadline' => '2026-08-15',
                'posted_on'            => '2026-05-10',
                'description'          => 'Punjab Animal Husbandry Department requires Veterinary Inspectors to monitor livestock health, conduct vaccination drives, prevent animal diseases, issue health certificates, and support dairy farmers across Punjab.',
                'qualifications'       => ['B.V.Sc. & A.H. degree', 'Registered with Punjab Veterinary Council', 'Age: 18-37 years', 'Valid driving license'],
            ],
            [
                'title'                => 'Block Primary Education Officer (BPEO)',
                'department'           => 'Department of School Education, Punjab',
                'location'             => 'Sangrur',
                'type'                 => 'government',
                'salary_range'         => '₹37,800 – ₹1,19,800',
                'vacancies'            => 55,
                'application_deadline' => '2026-08-20',
                'posted_on'            => '2026-05-11',
                'description'          => 'School Education Department Punjab is recruiting BPEOs to supervise and administer primary education in assigned blocks, monitor attendance, implement mid-day meal schemes, and ensure quality of education in government primary schools.',
                'qualifications'       => ['Master\'s degree with B.Ed.', 'PSTET qualified', '5+ years teaching experience', 'Age: 21-45 years'],
            ],
            [
                'title'                => 'Enforcement Inspector (Transport)',
                'department'           => 'Punjab State Transport Authority',
                'location'             => 'Chandigarh',
                'type'                 => 'government',
                'salary_range'         => '₹30,900 – ₹97,800',
                'vacancies'            => 40,
                'application_deadline' => '2026-07-28',
                'posted_on'            => '2026-05-09',
                'description'          => 'Punjab Transport Authority is hiring Enforcement Inspectors to check vehicle fitness, verify permits and licenses, enforce transport regulations, inspect buses/trucks for overloading, and take action against traffic violators.',
                'qualifications'       => ['Graduation in any stream', 'Valid LMV driving license', 'Age: 21-35 years', 'Knowledge of Punjab Motor Vehicle Act preferred'],
            ],
            [
                'title'                => 'District Child Protection Officer',
                'department'           => 'Department of Social Security & Women and Child Development',
                'location'             => 'Bathinda',
                'type'                 => 'government',
                'salary_range'         => '₹30,900 – ₹97,800',
                'vacancies'            => 22,
                'application_deadline' => '2026-07-22',
                'posted_on'            => '2026-05-08',
                'description'          => 'Punjab Social Security Department requires District Child Protection Officers to implement child protection schemes, manage childcare institutions, coordinate rescue operations for children in need, and maintain case records.',
                'qualifications'       => ['MSW / MA (Social Work) or MA (Psychology/Sociology)', 'Age: 21-40 years', '2 years experience in child welfare preferred'],
            ],
            [
                'title'                => 'SDO (Electrical)',
                'department'           => 'Punjab State Power Corporation Limited (PSPCL)',
                'location'             => 'Ludhiana',
                'type'                 => 'government',
                'salary_range'         => '₹47,600 – ₹1,51,100',
                'vacancies'            => 115,
                'application_deadline' => '2026-08-10',
                'posted_on'            => '2026-05-12',
                'description'          => 'PSPCL is recruiting Sub Divisional Officers (Electrical) to oversee power distribution, manage line gangs, supervise substation operations, reduce AT&C losses, and ensure uninterrupted electricity supply in assigned areas.',
                'qualifications'       => ['B.Tech / B.E. Electrical Engineering (60% marks)', 'Age: 18-37 years', 'GATE score preferred but not mandatory'],
            ],
            [
                'title'                => 'Pharmacist Grade-II',
                'department'           => 'Department of Health & Family Welfare, Punjab',
                'location'             => 'Gurdaspur',
                'type'                 => 'government',
                'salary_range'         => '₹22,700 – ₹72,000',
                'vacancies'            => 288,
                'application_deadline' => '2026-07-15',
                'posted_on'            => '2026-05-06',
                'description'          => 'Health Department Punjab is hiring Pharmacists for Government hospitals, CHCs and PHCs. Role involves dispensing medicines, maintaining drug inventory, preparing medicines, counselling patients, and ensuring drug store management at the facility.',
                'qualifications'       => ['D.Pharm or B.Pharm degree', 'Registered with Punjab Pharmacy Council', 'Age: 18-37 years'],
            ],
            [
                'title'                => 'Account Assistant (Cooperative Dept.)',
                'department'           => 'Department of Cooperation, Punjab',
                'location'             => 'Jalandhar',
                'type'                 => 'government',
                'salary_range'         => '₹19,900 – ₹63,200',
                'vacancies'            => 65,
                'application_deadline' => '2026-07-18',
                'posted_on'            => '2026-05-07',
                'description'          => 'Cooperation Department Punjab requires Account Assistants to maintain accounts of cooperative societies, prepare balance sheets, conduct internal audits, handle loan disbursements and recovery accounts for Milkfed and Markfed societies.',
                'qualifications'       => ['B.Com / M.Com', 'Tally knowledge required', 'Age: 18-35 years', 'Knowledge of cooperative societies preferred'],
            ],
            [
                'title'                => 'Clerk-cum-Data Entry Operator (CDEO)',
                'department'           => 'Punjab State Lotteries Department',
                'location'             => 'Chandigarh',
                'type'                 => 'government',
                'salary_range'         => '₹18,000 – ₹56,900',
                'vacancies'            => 48,
                'application_deadline' => '2026-07-05',
                'posted_on'            => '2026-05-10',
                'description'          => 'Punjab Lotteries Department requires CDEO to manage lottery sales data, enter draw results in the database, prepare reports, issue prize cheques, and handle public queries at lottery counters.',
                'qualifications'       => ['10+2 with Mathematics', 'Typing speed: 35 WPM', 'DCA certificate', 'Age: 18-35 years'],
            ],
            [
                'title'                => 'Fire Station Officer',
                'department'           => 'Punjab Fire Services',
                'location'             => 'Amritsar',
                'type'                 => 'government',
                'salary_range'         => '₹35,400 – ₹1,12,400',
                'vacancies'            => 38,
                'application_deadline' => '2026-08-05',
                'posted_on'            => '2026-05-11',
                'description'          => 'Punjab Fire Services is recruiting Fire Station Officers to lead firefighting operations, disaster rescue, hazmat incidents, and fire prevention inspections. Officers must be physically fit and ready to work 24x7 shifts.',
                'qualifications'       => ['Graduation (Science stream preferred)', 'Fire Engineering degree/diploma preferred', 'Age: 21-35 years', 'Physical fitness test mandatory', 'Swimming ability required'],
            ],
            [
                'title'                => 'District Horticulture Officer',
                'department'           => 'Department of Horticulture, Punjab',
                'location'             => 'Kapurthala',
                'type'                 => 'government',
                'salary_range'         => '₹35,400 – ₹1,12,400',
                'vacancies'            => 30,
                'application_deadline' => '2026-07-25',
                'posted_on'            => '2026-05-08',
                'description'          => 'Punjab Horticulture Department requires District Horticulture Officers to promote fruit/vegetable cultivation, distribute subsidies, provide technical guidance to farmers, supervise nurseries, and implement schemes like National Horticulture Mission.',
                'qualifications'       => ['B.Sc. Horticulture or Agriculture (Horticulture specialization)', 'Age: 21-37 years', 'Valid driving license'],
            ],

            // --- MORE PRIVATE SECTOR JOBS ---
            [
                'title'                => 'Full Stack Developer (Node.js + React)',
                'department'           => 'Nagarro Software Pvt. Ltd.',
                'location'             => 'Mohali',
                'type'                 => 'private',
                'salary_range'         => '₹60,000 – ₹1,20,000',
                'vacancies'            => 20,
                'application_deadline' => '2026-07-31',
                'posted_on'            => '2026-05-10',
                'description'          => 'Nagarro is looking for Full Stack Developers to build enterprise web applications for global clients. You will work with Node.js, React, MongoDB, and AWS. Agile/Scrum team environment with opportunities for international travel.',
                'qualifications'       => ['B.Tech CS/IT or MCA', '3+ years full-stack experience', 'Strong command of Node.js and React', 'Experience with cloud platforms (AWS/Azure/GCP)'],
            ],
            [
                'title'                => 'Production Supervisor (Textile)',
                'department'           => 'Trident Group Ltd.',
                'location'             => 'Ludhiana',
                'type'                 => 'private',
                'salary_range'         => '₹30,000 – ₹50,000',
                'vacancies'            => 18,
                'application_deadline' => '2026-07-20',
                'posted_on'            => '2026-05-08',
                'description'          => 'Trident Group, a leading textile manufacturer, requires Production Supervisors for its Ludhiana unit. Role includes supervising weaving/spinning operations, monitoring production targets, ensuring quality standards, and managing shift workers.',
                'qualifications'       => ['B.Tech Textile Engineering or Diploma in Textile Technology', '2-5 years production experience in textile industry', 'Knowledge of ISO quality standards'],
            ],
            [
                'title'                => 'HR Executive',
                'department'           => 'Hero Cycles Ltd.',
                'location'             => 'Ludhiana',
                'type'                 => 'private',
                'salary_range'         => '₹28,000 – ₹42,000',
                'vacancies'            => 6,
                'application_deadline' => '2026-07-15',
                'posted_on'            => '2026-05-09',
                'description'          => 'Hero Cycles Ltd. requires an HR Executive to handle end-to-end recruitment, onboarding, payroll processing, employee grievances, labour compliance, and HR reporting for their manufacturing plant.',
                'qualifications'       => ['MBA HR or PGDM HR', '2-4 years HR experience (manufacturing sector preferred)', 'Knowledge of PF/ESI/Labour laws'],
            ],
            [
                'title'                => 'Pharmacist (Retail Chemist)',
                'department'           => 'MedPlus Health Services Ltd.',
                'location'             => 'Jalandhar',
                'type'                 => 'private',
                'salary_range'         => '₹20,000 – ₹32,000',
                'vacancies'            => 25,
                'application_deadline' => '2026-06-30',
                'posted_on'            => '2026-05-07',
                'description'          => 'MedPlus, a leading pharmacy chain, is hiring registered Pharmacists for its Jalandhar outlets. Role includes dispensing medicines, counselling patients, maintaining stock records, managing expiry, and achieving sales targets for OTC products.',
                'qualifications'       => ['D.Pharm or B.Pharm', 'Registered with Punjab Pharmacy Council', 'Age: 21-35 years', 'Good communication skills'],
            ],
            [
                'title'                => 'Civil Site Engineer',
                'department'           => 'L&T Construction Ltd.',
                'location'             => 'Mohali',
                'type'                 => 'private',
                'salary_range'         => '₹35,000 – ₹65,000',
                'vacancies'            => 14,
                'application_deadline' => '2026-08-01',
                'posted_on'            => '2026-05-10',
                'description'          => 'L&T Construction is hiring Civil Site Engineers for residential and commercial projects in the Mohali/Chandigarh region. Responsibilities include site supervision, quality control, preparation of BOQ, coordination with contractors, and safety management.',
                'qualifications'       => ['B.E./B.Tech Civil Engineering', '2-5 years site experience', 'Knowledge of AutoCAD, MS Project', 'Willing to work on site'],
            ],
            [
                'title'                => 'Bank PO (Probationary Officer)',
                'department'           => 'Punjab & Sind Bank',
                'location'             => 'Chandigarh',
                'type'                 => 'private',
                'salary_range'         => '₹36,000 – ₹63,840',
                'vacancies'            => 40,
                'application_deadline' => '2026-07-28',
                'posted_on'            => '2026-05-11',
                'description'          => 'Punjab & Sind Bank is recruiting Probationary Officers for general banking operations. Selected candidates will be posted across Punjab branches and trained in retail banking, credit, customer service, and branch management.',
                'qualifications'       => ['Graduation with minimum 60%', 'Age: 20-30 years', 'Computer proficiency', 'IBPS PO exam score accepted'],
            ],
            [
                'title'                => 'Nursing Staff (ICU/General Ward)',
                'department'           => 'Fortis Hospital',
                'location'             => 'Mohali',
                'type'                 => 'private',
                'salary_range'         => '₹28,000 – ₹45,000',
                'vacancies'            => 35,
                'application_deadline' => '2026-07-10',
                'posted_on'            => '2026-05-09',
                'description'          => 'Fortis Hospital Mohali requires qualified Nursing Staff for ICU and general ward duty. Candidates must have hands-on experience in patient monitoring, IV cannulation, medication administration, and emergency procedures.',
                'qualifications'       => ['B.Sc. Nursing / GNM', 'Registered with Punjab Nursing Council', 'ICU experience preferred for ICU postings', '1+ year experience'],
            ],
            [
                'title'                => 'AutoCAD Draftsman',
                'department'           => 'Omaxe Ltd.',
                'location'             => 'Amritsar',
                'type'                 => 'private',
                'salary_range'         => '₹20,000 – ₹32,000',
                'vacancies'            => 8,
                'application_deadline' => '2026-07-18',
                'posted_on'            => '2026-05-08',
                'description'          => 'Omaxe Ltd. is seeking AutoCAD Draftsmen for their Amritsar real estate projects. The role involves preparing architectural and structural drawings, layout plans, working drawings, and as-built drawings using AutoCAD 2D/3D.',
                'qualifications'       => ['Diploma in Civil / Architecture', 'Proficiency in AutoCAD 2D & 3D', '2+ years drafting experience', 'Knowledge of building codes preferred'],
            ],
            [
                'title'                => 'Delivery Executive (E-Commerce)',
                'department'           => 'Amazon India Pvt. Ltd.',
                'location'             => 'Ludhiana',
                'type'                 => 'private',
                'salary_range'         => '₹15,000 – ₹22,000 + incentives',
                'vacancies'            => 150,
                'application_deadline' => '2026-06-25',
                'posted_on'            => '2026-05-05',
                'description'          => 'Amazon India is hiring Delivery Executives (DEA) for its Ludhiana delivery station. Responsibilities include package pickup from station, route-based delivery to customers, using Amazon delivery app, and maintaining delivery performance metrics.',
                'qualifications'       => ['10th pass minimum', 'Valid two-wheeler driving license', 'Own bike with insurance', 'Age: 20-40 years', 'Android smartphone required'],
            ],
            [
                'title'                => 'Content Writer (Punjabi/Hindi)',
                'department'           => 'Jagran Prakashan Ltd.',
                'location'             => 'Jalandhar',
                'type'                 => 'private',
                'salary_range'         => '₹18,000 – ₹28,000',
                'vacancies'            => 10,
                'application_deadline' => '2026-07-05',
                'posted_on'            => '2026-05-06',
                'description'          => 'Jagran Prakashan Ltd. (Dainik Jagran) requires Content Writers for their digital news platform covering Punjab news. Role involves writing news articles in Punjabi/Hindi, SEO optimization of content, social media posting, and managing news updates.',
                'qualifications'       => ['Graduation (Journalism/Mass Communication preferred)', 'Excellent Punjabi and Hindi writing skills', 'Knowledge of current affairs', 'Typing speed in Punjabi/Hindi required'],
            ],
            [
                'title'                => 'Hotel Receptionist',
                'department'           => 'Taj Hotel & Resorts',
                'location'             => 'Amritsar',
                'type'                 => 'private',
                'salary_range'         => '₹22,000 – ₹32,000',
                'vacancies'            => 12,
                'application_deadline' => '2026-07-12',
                'posted_on'            => '2026-05-10',
                'description'          => 'Taj Hotel Amritsar (near Golden Temple) is hiring Receptionists for front desk operations. Duties include guest check-in/check-out, reservation management using Opera PMS, handling guest queries, coordinating with housekeeping, and providing premium hospitality.',
                'qualifications'       => ['Diploma/Degree in Hotel Management or Tourism', 'Excellent English communication skills', 'Knowledge of Opera/IDS hotel software preferred', '1+ year front desk experience'],
            ],
            [
                'title'                => 'Diesel Mechanic',
                'department'           => 'Tata Motors Ltd. – Authorized Service Center',
                'location'             => 'Patiala',
                'type'                 => 'private',
                'salary_range'         => '₹20,000 – ₹32,000',
                'vacancies'            => 20,
                'application_deadline' => '2026-07-08',
                'posted_on'            => '2026-05-07',
                'description'          => 'Tata Motors authorized service center in Patiala requires Diesel Mechanics for servicing, repair, and maintenance of commercial vehicles including trucks, buses and LCVs. Hands-on experience in diesel engines, hydraulics, and transmission systems required.',
                'qualifications'       => ['ITI (Diesel Mechanic trade) or Mechanic Motor Vehicle', 'NAC/ATS certificate preferred', '2+ years commercial vehicle experience', 'Knowledge of diagnostics tools'],
            ],
            [
                'title'                => 'CNC Machine Operator',
                'department'           => 'Bharat Forge Ltd.',
                'location'             => 'Ludhiana',
                'type'                 => 'private',
                'salary_range'         => '₹22,000 – ₹38,000',
                'vacancies'            => 30,
                'application_deadline' => '2026-07-22',
                'posted_on'            => '2026-05-09',
                'description'          => 'Bharat Forge Ludhiana Plant requires CNC Machine Operators for precision machining of auto components. Role involves operating CNC Turning/VMC machines, setting up tools and fixtures, conducting first article inspection, and maintaining machining quality.',
                'qualifications'       => ['ITI (Turner/Fitter/Machinist) or Diploma in Mechanical', 'CNC programming knowledge (Fanuc/Siemens)', '2+ years CNC operation experience', 'Quality consciousness required'],
            ],
            [
                'title'                => 'Dietitian / Nutritionist',
                'department'           => 'Max Super Speciality Hospital',
                'location'             => 'Mohali',
                'type'                 => 'private',
                'salary_range'         => '₹30,000 – ₹48,000',
                'vacancies'            => 4,
                'application_deadline' => '2026-07-25',
                'posted_on'            => '2026-05-11',
                'description'          => 'Max Hospital Mohali is looking for a qualified Dietitian to prepare therapeutic diet plans for patients, conduct nutrition counselling, manage hospital kitchen dietary standards, and coordinate with the medical team for ICU/CCU nutritional support.',
                'qualifications'       => ['B.Sc. / M.Sc. Food & Nutrition or Dietetics', 'RD (Registered Dietitian) certification preferred', '2+ years clinical dietetics experience'],
            ],
            [
                'title'                => 'Field Sales Officer (FMCG)',
                'department'           => 'Nestle India Ltd.',
                'location'             => 'Chandigarh',
                'type'                 => 'private',
                'salary_range'         => '₹25,000 – ₹40,000 + incentives',
                'vacancies'            => 22,
                'application_deadline' => '2026-07-18',
                'posted_on'            => '2026-05-10',
                'description'          => 'Nestle India is hiring Field Sales Officers for its Chandigarh region to drive distribution and sales of food & beverage products. Role involves managing distributor relationships, expanding retail coverage, achieving monthly targets, and conducting market surveys.',
                'qualifications'       => ['Graduation in any stream', '1-3 years FMCG sales experience', 'Two-wheeler with valid DL', 'Good market knowledge of Punjab/Chandigarh region'],
            ],
        ];

        foreach ($jobs as $j) {
            Job::firstOrCreate(
                ['title' => $j['title'], 'department' => $j['department']],
                array_merge($j, [
                    'is_active'  => true,
                    'posted_on'  => $j['posted_on'] ?? now()->toDateString(),
                    'qualifications' => json_encode($j['qualifications'] ?? []),
                ])
            );
        }

        // ── Sample Trainings ──────────────────────────────────────────────────
        $trainings = [
            // IT
            ['title' => 'Web Development Bootcamp',              'provider' => 'Punjab Skill Mission',      'category' => 'IT',           'duration' => '3 months', 'total_seats' => 30, 'fee' => 'Free',   'description' => 'Comprehensive training in HTML, CSS, JavaScript, React and PHP for web development jobs.'],
            ['title' => 'Mobile Phone Repair',                   'provider' => 'Punjab Skill Mission',      'category' => 'IT',           'duration' => '45 days',  'total_seats' => 35, 'fee' => 'Free',   'description' => 'Learn to diagnose and repair smartphones, tablets, and feature phones. Hardware and software troubleshooting.'],
            ['title' => 'Python Programming for Beginners',      'provider' => 'CDAC Mohali',               'category' => 'IT',           'duration' => '2 months', 'total_seats' => 40, 'fee' => '₹500',   'description' => 'Beginner to intermediate Python programming covering data types, loops, functions, file handling and basic automation scripts.'],
            ['title' => 'Cyber Security Fundamentals',           'provider' => 'PICTC Chandigarh',          'category' => 'IT',           'duration' => '2 months', 'total_seats' => 25, 'fee' => '₹1,000', 'description' => 'Introduction to cybersecurity including network security, ethical hacking basics, firewall configuration and data protection laws.'],
            ['title' => 'MS Office & Computer Basics',           'provider' => 'PGRKAM Training Centre',    'category' => 'IT',           'duration' => '1 month',  'total_seats' => 60, 'fee' => 'Free',   'description' => 'Practical training in MS Word, Excel, PowerPoint, email, internet browsing and basic computer operations for government job aspirants.'],
            ['title' => 'Data Entry & Typing Course',            'provider' => 'Punjab Skill Mission',      'category' => 'IT',           'duration' => '45 days',  'total_seats' => 50, 'fee' => 'Free',   'description' => 'Speed typing training in English and Punjabi (Gurmukhi), along with data entry skills required for government clerk and DEO positions.'],
            ['title' => 'Android App Development',               'provider' => 'NIIT Ludhiana',             'category' => 'IT',           'duration' => '3 months', 'total_seats' => 20, 'fee' => '₹2,000', 'description' => 'Hands-on training in Android app development using Kotlin, Android Studio, REST API integration, Firebase and Play Store deployment.'],
            // Electrical
            ['title' => 'Electrician Trade Course',              'provider' => 'ITI Ludhiana',              'category' => 'Electrical',   'duration' => '6 months', 'total_seats' => 25, 'fee' => 'Free',   'description' => 'Government ITI affiliated course covering wiring, switchgear, motor rewinding and industrial electrical work.'],
            ['title' => 'Solar Panel Installation & Repair',     'provider' => 'Punjab Energy Dev. Agency', 'category' => 'Electrical',   'duration' => '2 months', 'total_seats' => 30, 'fee' => 'Free',   'description' => 'Training on installation, commissioning and maintenance of solar rooftop systems, inverters, charge controllers and net metering connections.'],
            ['title' => 'Industrial Electrician (Advanced)',     'provider' => 'ITI Patiala',               'category' => 'Electrical',   'duration' => '4 months', 'total_seats' => 20, 'fee' => 'Free',   'description' => 'Advanced course covering PLC programming, industrial automation, motor control panels, VFDs and electrical safety standards for factory environments.'],
            ['title' => 'AC & Refrigeration Technician',         'provider' => 'Punjab Skill Dev. Corp.',   'category' => 'Electrical',   'duration' => '3 months', 'total_seats' => 25, 'fee' => '₹500',   'description' => 'Technical training on installation, servicing and repair of window ACs, split ACs, refrigerators, and commercial cold storage systems.'],
            // Marketing
            ['title' => 'Digital Marketing Certification',       'provider' => 'CDAC Mohali',               'category' => 'Marketing',    'duration' => '2 months', 'total_seats' => 40, 'fee' => '₹500',   'description' => 'Practical training in Google Ads, Meta Ads, SEO, content marketing and social media management.'],
            ['title' => 'Tally & GST Accounting',                'provider' => 'NIIT Jalandhar',            'category' => 'Marketing',    'duration' => '2 months', 'total_seats' => 30, 'fee' => '₹1,000', 'description' => 'Complete training in Tally Prime, GST filing, TDS, invoicing and financial statement preparation.'],
            ['title' => 'Sales & Retail Management',             'provider' => 'PGRKAM Training Centre',    'category' => 'Marketing',    'duration' => '6 weeks',  'total_seats' => 40, 'fee' => 'Free',   'description' => 'Training in retail sales techniques, customer handling, billing systems, inventory management and visual merchandising for mall and showroom jobs.'],
            ['title' => 'Banking & Finance Fundamentals',        'provider' => 'Punjab National Bank',      'category' => 'Marketing',    'duration' => '1 month',  'total_seats' => 35, 'fee' => 'Free',   'description' => 'Introduction to banking operations, savings & current accounts, loans, insurance products and IBPS exam preparation for banking job aspirants.'],
            ['title' => 'E-Commerce & Online Selling',           'provider' => 'Punjab Skill Mission',      'category' => 'Marketing',    'duration' => '6 weeks',  'total_seats' => 30, 'fee' => 'Free',   'description' => 'Training on selling products on Amazon, Flipkart, and Meesho. Product photography, listing optimization, order management, and payment processing.'],
            // Handcraft
            ['title' => 'Tailoring & Garment Making',            'provider' => 'Women Empowerment ITI',     'category' => 'Handcraft',    'duration' => '4 months', 'total_seats' => 20, 'fee' => 'Free',   'description' => 'Hands-on training in stitching, pattern making, boutique management for women empowerment.'],
            ['title' => 'Beauty & Wellness (Cosmetology)',       'provider' => 'Lakme Training Academy',    'category' => 'Handcraft',    'duration' => '3 months', 'total_seats' => 20, 'fee' => '₹2,000', 'description' => 'Professional training in skin care, hair styling, makeup artistry and salon management for self-employment.'],
            ['title' => 'Phulkari & Punjabi Embroidery',         'provider' => 'Crafts Council Punjab',     'category' => 'Handcraft',    'duration' => '3 months', 'total_seats' => 25, 'fee' => 'Free',   'description' => 'Traditional Phulkari embroidery training for women to revive Punjab heritage craft and generate self-employment through e-commerce platforms.'],
            ['title' => 'Pottery & Ceramic Art',                 'provider' => 'Punjab Lalit Kala Akademi', 'category' => 'Handcraft',   'duration' => '2 months', 'total_seats' => 15, 'fee' => '₹500',   'description' => 'Wheel throwing, hand building, glazing and kiln firing techniques for traditional pottery and modern decorative ceramics with market linkage support.'],
            ['title' => 'Furniture & Carpentry Skills',          'provider' => 'ITI Amritsar',              'category' => 'Handcraft',    'duration' => '6 months', 'total_seats' => 20, 'fee' => 'Free',   'description' => 'Wood furniture making, carpentry tools, polishing, and interior fittings training for self-employment and construction sector jobs.'],
            // Communication
            ['title' => 'Spoken English & Soft Skills',          'provider' => 'PGRKAM Training Centre',    'category' => 'Communication','duration' => '1 month',  'total_seats' => 50, 'fee' => 'Free',   'description' => 'Improve spoken English, interview skills, professional communication and personality development.'],
            ['title' => 'Interview Preparation & Resume Writing', 'provider' => 'PGRKAM Training Centre',   'category' => 'Communication','duration' => '2 weeks',  'total_seats' => 60, 'fee' => 'Free',   'description' => 'Practical workshop on resume writing, LinkedIn profile building, mock interviews, group discussions and workplace etiquette for job seekers.'],
            ['title' => 'Customer Service Excellence',            'provider' => 'Concentrix Academy',        'category' => 'Communication','duration' => '3 weeks',  'total_seats' => 45, 'fee' => 'Free',   'description' => 'Professional training in call handling, complaint resolution, CRM tools, email writing and customer satisfaction techniques for BPO and hospitality jobs.'],
            ['title' => 'Public Speaking & Personality Dev.',     'provider' => 'PGRKAM Training Centre',    'category' => 'Communication','duration' => '1 month',  'total_seats' => 40, 'fee' => 'Free',   'description' => 'Build confidence in public speaking, group presentations, debate skills, body language and professional grooming for interview and workplace success.'],
            ['title' => 'Legal Literacy & Consumer Rights',       'provider' => 'Punjab State Legal Serv.',  'category' => 'Communication','duration' => '2 weeks',  'total_seats' => 50, 'fee' => 'Free',   'description' => 'Awareness program on labour laws, consumer rights, RTI Act, legal aid schemes and women safety laws for educated job seekers in Punjab.'],
        ];

        foreach ($trainings as $t) {
            Training::firstOrCreate(['title' => $t['title']], array_merge($t, ['is_active' => true]));
        }

        // ── Sample Notifications for all users ───────────────────────────────
        $allUsers = User::where('role', 'user')->get();
        foreach ($allUsers as $seedUser) {
            // Only skip if they already have the Welcome seed notification
            if (Notification::where('user_id', $seedUser->id)->where('title', 'Welcome to PGRKAM!')->exists()) continue;
            $notifs = [
                [
                    'title'      => 'Welcome to PGRKAM!',
                    'message'    => 'Your account has been created successfully. Start exploring government and private job opportunities across Punjab.',
                    'type'       => 'info',
                    'link'       => '/dashboard',
                    'is_read'    => true,
                    'created_at' => now()->subDays(3),
                    'updated_at' => now()->subDays(3),
                ],
                [
                    'title'      => 'Resume Incomplete',
                    'message'    => 'Complete your resume to increase your chances of getting shortlisted. Add your skills and work experience.',
                    'type'       => 'alert',
                    'link'       => '/resume',
                    'is_read'    => false,
                    'created_at' => now()->subDays(2),
                    'updated_at' => now()->subDays(2),
                ],
                [
                    'title'      => 'New Jobs Available',
                    'message'    => 'New Government and private jobs matching your profile are available in Punjab. Browse and apply before the deadline!',
                    'type'       => 'job',
                    'link'       => '/jobs',
                    'is_read'    => false,
                    'created_at' => now()->subHours(5),
                    'updated_at' => now()->subHours(5),
                ],
            ];
            if ($seedUser->email === 'user@pgrkam.gov.in') {
                $notifs[] = [
                    'title'      => 'Application Submitted',
                    'message'    => 'Your application for "Junior Clerk" at Revenue Dept. has been received. Reference: PGRKAM-2026-EB44F324',
                    'type'       => 'job',
                    'link'       => '/my-applications',
                    'is_read'    => false,
                    'created_at' => now()->subMinutes(30),
                    'updated_at' => now()->subMinutes(30),
                ];
                $notifs[] = [
                    'title'      => 'Training Enrollment Confirmed',
                    'message'    => 'You have been successfully enrolled in "Web Development Bootcamp" by Punjab Skill Mission.',
                    'type'       => 'training',
                    'link'       => '/my-enrollments',
                    'is_read'    => false,
                    'created_at' => now()->subHours(2),
                    'updated_at' => now()->subHours(2),
                ];
            }
            foreach ($notifs as $n) {
                Notification::create(array_merge($n, ['user_id' => $seedUser->id]));
            }
        }

        $this->command->info('✅ PGRKAM database seeded with real Punjab job data!');
        $this->command->info('   Admin: admin@pgrkam.gov.in / password');
        $this->command->info('   User:  user@pgrkam.gov.in  / password');
    }
}
